version: '{build}'

image:
  - Visual Studio 2013
  
environment:
  sln_name: zmq
  project_name: zmq-source

configuration:
  - Release

install:
  - git submodule update --init --recursive

build:
  project: src\%sln_name%\%sln_name%.sln

artifacts:
  - path: 'src\%sln_name%\%CONFIGURATION%\%project_name%.exe'
  - path: 'src\%sln_name%\%CONFIGURATION%\*.dll'
